### PR TITLE
[MB-53810] Don't allow any dist connection if cookie is nocookie

### PR DESCRIPTION
**Pull request by bryandmc**
@timofey-barmin I had to solve some conflicts so I definitely need you to review before moving forward. I think I adapted the patch correctly, but obviously I could be wrong. 

PS. I am just putting this here to review (only!), I will push wherever ceej wants it once we've reviewed it or force push again to this branch so we don't accidentally create a merge commit.

### CODE REVIEW

**Comment by timofey-barmin** [comment]
LGTM,
could you please test that it actually fixes the issue in CC (see steps in the original ticket).

**Comment by bryandmc** [comment]
> LGTM, could you please test that it actually fixes the issue in CC (see steps in the original ticket).

Yes I will check that out as well.

**Comment by bryandmc** [comment]
So I tested it out and I think it works because now we cannot connect like in your example on the ticket. Just to be clear, we are supposed to have the connections rejected by our normal (ns_server) node, right? because it rejects it saying that:

> [error_logger:error,2022-10-18T15:49:11.457-07:00,n_0@cb.local:<0.1138.0>:ale_error_logger_handler:do_log:101]
> =========================ERROR REPORT=========================
> ** Connection attempt to/from node 'n_666@127.0.0.1' rejected. Cookie is not set. **

But I admit I haven't tried the unpatched CC erlang yet..

**Comment by bryandmc** [comment]
FYI I had to add 2 extra patches to fix the Mac OS build. That's all they are for.

**Comment by timofey-barmin** [comment]
LGTM

**Pull request merged**
