### PR TITLE
Patches for upgrade 22.3

### PR DESCRIPTION
**Pull request by anuthan**
@timofey-barmin  @aartamonau  @vzasade  @stevewatanabe @dave-finlay @samcramer
Can you guys review it?

### CODE REVIEW

**Comment by anuthan** [comment]
@aartamonau  Did what you suggested.

**Comment by timofey-barmin** [comment]
The commits look ok. What about other patches from mad-hatter branch? Do you plan to apply them as well?

**Comment by anuthan** [comment]
Few of them yes. Except for backports and change for MB-37420(which I'm evaluating if we can use the custom hostname check which will be part of ns_server, else will cherry-pick that too).

**Comment by anuthan** [comment]
@timofey-barmin and @aartamonau : Added your previous commits to couchbase-madhatter branch here as well.  Actually wanted to push them as a seperate PR but forgot github updates the PR when I push to my github account. 
Can you guys please re-review?

**Comment by timofey-barmin** [comment]
What about this commit https://github.com/couchbasedeps/erlang/commit/d27c692326c15ad4e01bdb5a9244b5da7aa6af17?
Do we need it?

**Comment by anuthan** [comment]
Looks like we don't need d27c692. See, https://github.com/couchbasedeps/erlang/pull/6/commits/0dd081152fe60ae2acb4cc21d9872df858cbe3d8

**Comment by timofey-barmin** [comment]
Yeah, looks like they gave up on their idea of using node name in SNI

**Comment by timofey-barmin** [comment]
LGTM

**Pull request merged**
